export const APP_CHANGE_LOADING_STATE = 'APP/CHANGE_LOADING_STATE';
export const APP_CLEAR_STATE = 'APP/CLEAR_STATE';

export const APP_GET_PROFILE_REQUEST = 'APP/GET_PROFILE/REQUEST';
export const APP_GET_PROFILE_SUCCESS = 'APP/GET_PROFILE/SUCCESS';
export const APP_GET_PROFILE_ERROR = 'APP/GET_PROFILE/ERROR';

export const APP_UPDATE_PROFILE_REQUEST = 'APP/UPDATE_PROFILE/REQUEST';
export const APP_UPDATE_PROFILE_SUCCESS = 'APP/UPDATE_PROFILE/SUCCESS';
export const APP_UPDATE_PROFILE_ERROR = 'APP/UPDATE_PROFILE/ERROR';