# Generated by Django 2.2.24 on 2021-07-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210708_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Conforming', 'Non-Conforming'), ('Prefer not to Say', 'Prefer not to Say')], max_length=50, null=True, verbose_name='Gender of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='school_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='School code'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zip code'),
        ),
    ]
